version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/Frontend"
    schedule:
      interval: "weekly"
      day: "monday"
    open-pull-requests-limit: 1
    groups:
      frontend-dependencies:
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"

  - package-ecosystem: "gradle"
    directory: "/Backend"
    schedule:
      interval: "weekly"
      day: "monday"
    open-pull-requests-limit: 1
    groups:
      backend-dependencies:
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
    open-pull-requests-limit: 1
    groups:
      github-actions:
        patterns:
          - "*"
