version: '3.8'

services:
  # 1. MySQL 데이터베이스
  mysql:
    image: mysql:8.0
    container_name: tardis_mysql
    environment:
      MYSQL_ROOT_PASSWORD: 1234 # 스프링 부트 application.yaml의 비밀번호와 일치시키세요!
      MYSQL_DATABASE: tardis_db
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  # 2. Redis (추후 웹소켓이나 캐싱에 사용할 수 있도록 살려둡니다)
  redis:
    image: redis:7-alpine
    container_name: tardis_redis
    ports:
      - "6379:6379"

volumes:
  mysql_data:
